(require "auto.rkt")

(define accommodator
  (automaton 1
             (list (state 0 (list (action 0 2)
                                  (action 1 1)
                                  (action 2 0)))
                   (state 1 (list (action 0 2)
                                    (action 1 1)
                                    (action 2 0)))
                   (state 2 (list (action 0 2)
                                  (action 1 1)
                                  (action 2 0)))
                   (state 0 (list (action 0 2)
                                  (action 1 2)
                                  (action 2 2)))
                   (state 0 (list (action 0 2)
                                  (action 1 2)
                                  (action 2 2))))))
(define all-highs
  (automaton 2
             (list (state 2 (list (action 0 2)
                                  (action 1 2)
                                  (action 2 2)))
                   (state 2 (list (action 0 2)
                                  (action 1 2)
                                  (action 2 2)))
                   (state 2 (list (action 0 2)
                                  (action 1 2)
                                  (action 2 2)))
                   (state 2 (list (action 0 2)
                                  (action 1 2)
                                  (action 2 2)))
                   (state 2 (list (action 0 2)
                                  (action 1 2)
                                  (action 2 2)))
                   )))
